upload:
  config:
    isFTP: false
    path: /uploads
  ftp:
    hostname:
    port:
    username:
    password:
    path:
    displaypath:
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB